practice-for-ch-rails-music-app-long-practice-main/music_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:create, :destroy, :new]
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/models/user.rb
class User < ApplicationRecord
    before_validation :ensure_session_token

    validates :email, uniqueness: true, presence: true
    validates :session_token, presence: true 
    validates :password, length: {minimum: 6}, allow_nil: true

    attr_reader :password

    def find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def is_password?(password)
        pass_obj = BCrypt::Password.new(self.password_digest)
        pass_obj.is_password?(password)
    end
    
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/controllers/application_controller.rb
# CR(R)LLL - ApplicationController
    # current_user
    # require_logged_in
    # require_logged_out
    # login!(user)
    # logged_in?
    # logout



class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    # skip_before_action :verify_authenticity_token

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token! # reset and save a new session token to cookie at this stage to prevent data breach
    end

    def require_logged_in
        redirect_to session_url unless logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in? # user singular would need an "id" put in
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

    

end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    # before_action :require_logged_out, only: [:new, :create]
    # before_action :require_logged_in, only: [:destroy]

    # helper_method :logged_in?, :current_user
    def new
        @user = User.new 
        render :new
    end

    def create
        email = params[:user][:email]
        password = params[:user][:password]

        @user = User.find_by_credentials(email, password)

        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            @user = User.new(email: email)
            flash.now[:errors] = ["Dammit"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
    
    
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_out, only: [:new, :create]
    before_action :require_logged_in, only: [:show]

    def index
        @users = User.all
        render :index
    end

    def new
        @user = User.new
        render :new
    end

    def create
        @user= User.new(user_params)
         if @user.save 
            login!(@user)
            redirect_to user_url(@user) # redirect to page
         else
            flash.now[:errors] = @user.errors.full_messages
            render :new
         end
     end

     def show
        @user = User.find(params[:id])
        render :show
     end
 
     private
 
     def user_params
         params.require(:user).permit(:email, :password)
     end
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'/>".html_safe # study this last tag
    end
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/helpers/users_helper.rb
module UsersHelper
end

practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

    <% if logged_in? %>
      <h2>Hello current logged in user</h2>
      <form action="<%= session_url %>" method="POST">

        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
        <input type="submit" value="Logout">
      </form>

    <% else %>
        <a href="<%= new_user_url%>">Sign Up</a>
        <a href="<% new_session_url%>">Login</a>
    <% end %>




    <%= yield %>
  </body>
</html>

practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/users/_user.html.erb
<!-- <li><%= user.email %></li> -->

<!-- <% if action == :from%> -->

practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/users/new.html.erb
<h1>Create New User</h1>

<input type="hidden" name="authenticity_token" value='#{form_authenticity_token}'/>

<form action="<%= users_url %>" method="POST">

    <label for="email">Email:
        <input type="text" id="email" name="user[email]" value="<%= @user.email %>">
    </label>

    <br>
    <br>

    <label for="password">Password:
        <input type="password" id="password" name="user[password]" value="">
    </label>

    <input type="submit" value="Create User">


</form>



practice-for-ch-rails-music-app-long-practice-main/music_app/app/views/users/show.html.erb
<h1>User Email</h1>

<%= render 'user', user: @user, action: :from_show_page %>